#pragma once

#define NSIS_MAX_STRLEN 1024
#define _chdir chdir
#define NSIS_MAX_INST_TYPES 32
#define NSIS_CONFIG_VISIBLE_SUPPORT
#define NSIS_CONFIG_PLUGIN_SUPPORT
#define NSIS_SUPPORT_MESSAGEBOX
#define NSIS_SUPPORT_DELETE
#define NSIS_SUPPORT_FNUTIL
#define NSIS_SUPPORT_RMDIR
#define NSIS_SUPPORT_FILE
#define NSIS_SUPPORT_ACTIVEXREG
#define NSIS_SUPPORT_STACK
#define NSIS_SUPPORT_STROPTS
#define NSIS_SUPPORT_VERSION_INFO
#define NSIS_SUPPORT_REGISTRYFUNCTIONS
#define NSIS_SUPPORT_EXECUTE
#define NSIS_SUPPORT_CREATESHORTCUT

#define NSIS_VARS_SECTION ".ndata"

#ifndef S_OK
#define S_OK 0
#endif

#ifndef NSISCALL
#define NSISCALL
#endif
